using System;

class Prgram
{
    static void Main()
    {
        
        try
        {

            
            //nested vode block
            try
            {
               Console.WriteLine("Enter a number to divide 6 by");
                int divisor = Convert.ToInt32(Console.ReadLine());

                int divideByZero = 6 / divisor;
                Console.WriteLine("6 divided by " + divisor + " is " + divideByZero);
            }
            // inner catch block
            catch (Exception e)
            {
                Console.WriteLine("Inner catch is executed " + e.Message);
            }
        }
        // outer ctach block
        catch (DivideByZeroException e)
        {
              Console.WriteLine("Outer catch is executed" + e.Message); 
        }
    }
}
